import { EItem } from "./enums/items";
import { EMonster } from "./enums/monsters";

export const MonsterDrops: Partial<Record<EItem, EMonster[]>> = {
    // Raids
    // COX
    [EItem.OLMLET]: [],
    [EItem.METAMORPHIC_DUST]: [],
    [EItem.TWISTED_ANCESTRAL_COLOUR_KIT]: [],
    [EItem.ARCANE_PRAYER_SCROLL]: [],
    [EItem.DEXTEROUS_PRAYER_SCROLL]: [],
    [EItem.DINHS_BULWARK]: [],
    [EItem.ANCESTRAL_ROBE_BOTTOM]: [],
    [EItem.ANCESTRAL_ROBE_TOP]: [],
    [EItem.ANCESTRAL_HAT]: [],
    [EItem.DRAGON_CLAWS]: [],
    [EItem.KODAI_INSIGNIA]: [],
    [EItem.ELDER_MAUL]: [],
    [EItem.TWISTED_BOW]: [],

    // TOB
    [EItem.LIL_ZIK]: [],
    [EItem.SANGUINE_DUST]: [],
    [EItem.HOLY_ORNAMENT_KIT]: [],
    [EItem.SANGUINE_ORNAMENT_KIT]: [],
    [EItem.AVERNIC_DEFENDER_HILT]: [],
    [EItem.JUSTICIAR_LEGGUARDS]: [],
    [EItem.JUSTICIAR_CHESTGUARD]: [],
    [EItem.JUSTICIAR_FACEGUARD]: [],
    [EItem.SANGUINESTI_STAFF_UNCHARGED]: [],
    [EItem.GHRAZI_RAPIER]: [],
    [EItem.SCYTHE_OF_VITUR_UNCHARGED]: [],

    // TOA
    [EItem.TUMEKENS_GUARDIAN]: [],
    [EItem.LIGHTBEARER]: [],
    [EItem.OSMUMTENS_FANG]: [],
    [EItem.ELIDINIS_WARD]: [],
    [EItem.MASORI_CHAPS]: [],
    [EItem.MASORI_BODY]: [],
    [EItem.MASORI_MASK]: [],
    [EItem.TUMEKENS_SHADOW_UNCHARGED]: [],
    [EItem.MASORI_CRAFTING_KIT]: [],
    [EItem.MENAPHITE_ORNAMENT_KIT]: [],
    [EItem.CURSED_PHALANX]: [],
    [EItem.REMNANT_OF_AKKHA]: [],
    [EItem.REMNANT_OF_BABA]: [],
    [EItem.REMNANT_OF_KEPHRI]: [],
    [EItem.REMNANT_OF_ZEBAK]: [],
    [EItem.ANCIENT_REMNANT]: [],

    // DT2
    // Duke Sucellus
    [EItem.BARON]: [],
    [EItem.EYE_OF_THE_DUKE]: [],
    [EItem.MAGUS_VESTIGE]: [],

    // The Leviathan
    [EItem.LILVIATHAN]: [],
    [EItem.LEVIATHANS_LURE]: [],
    [EItem.VENATOR_VESTIGE]: [],

    // Vardorvis
    [EItem.BUTCH]: [],
    [EItem.EXECUTIONERS_AXE_HEAD]: [],
    [EItem.ULTOR_VESTIGE]: [],

    // The Whisperer
    [EItem.WISP]: [],
    [EItem.SIRENS_STAFF]: [],
    [EItem.BELLATOR_VESTIGE]: [],

    [EItem.VIRTUS_MASK]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],
    [EItem.VIRTUS_ROBE_TOP]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],
    [EItem.VIRTUS_ROBE_BOTTOM]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],
    [EItem.CHROMIUM_INGOT]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],
    [EItem.AWAKENERS_ORB]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],
    [EItem.GOLD_RING]: [
        EMonster.VARDORVIS,
        EMonster.THE_WHISPERER,
        EMonster.DUKE_SUCELLUS,
        EMonster.THE_LEVIATHAN,
    ],

    //GWD
    [EItem.BANDOS_CHESTPLATE]: [],
    [EItem.BANDOS_TASSETS]: [],
    [EItem.BANDOS_BOOTS]: [],
    [EItem.BANDOS_HILT]: [],
    [EItem.PET_GENERAL_GRAARDOR]: [],

    [EItem.ARMADYL_CROSSBOW]: [],
    [EItem.SARADOMIN_HILT]: [],
    [EItem.SARADOMIN_SWORD]: [],
    [EItem.SARADOMINS_LIGHT]: [],
    [EItem.PET_ZILYANA]: [],

    [EItem.ARMADYL_HELMET]: [],
    [EItem.ARMADYL_CHESTPLATE]: [],
    [EItem.ARMADYL_CHAINSKIRT]: [],
    [EItem.ARMADYL_HILT]: [],
    [EItem.PET_KREEARRA]: [],

    [EItem.STAFF_OF_THE_DEAD]: [],
    [EItem.ZAMORAKIAN_SPEAR]: [],
    [EItem.STEAM_BATTLESTAFF]: [],
    [EItem.ZAMORAK_HILT]: [],
    [EItem.PET_KRIL_TSUTSAROTH]: [],

    [EItem.GODSWORD_SHARD_1]: [
        EMonster.GENERAL_GRAARDOR,
        EMonster.COMMANDER_ZILYANA,
        EMonster.KREEARRA,
        EMonster.KRIL_TSUTSAROTH,
    ],
    [EItem.GODSWORD_SHARD_2]: [
        EMonster.GENERAL_GRAARDOR,
        EMonster.COMMANDER_ZILYANA,
        EMonster.KREEARRA,
        EMonster.KRIL_TSUTSAROTH,
    ],
    [EItem.GODSWORD_SHARD_3]: [
        EMonster.GENERAL_GRAARDOR,
        EMonster.COMMANDER_ZILYANA,
        EMonster.KREEARRA,
        EMonster.KRIL_TSUTSAROTH,
    ],

    [EItem.ANCIENT_HILT]: [],
    [EItem.NIHIL_HORN]: [],
    [EItem.ZARYTE_VAMBRACES]: [],
    [EItem.TORVA_FULL_HELM_DAMAGED]: [],
    [EItem.TORVA_PLATEBODY_DAMAGED]: [],
    [EItem.TORVA_PLATELEGS_DAMAGED]: [],
    [EItem.NEXLING]: [],

    // Abyssal Sire
    [EItem.JAR_OF_MIASMA]: [],
    [EItem.BLUDGEON_AXON]: [],
    [EItem.BLUDGEON_CLAW]: [],
    [EItem.BLUDGEON_SPINE]: [],
    [EItem.ABYSSAL_DAGGER]: [EMonster.ABYSSAL_SIRE, EMonster.ABYSSAL_DEMON],
    [EItem.ABYSSAL_WHIP]: [EMonster.ABYSSAL_SIRE, EMonster.ABYSSAL_DEMON],
    [EItem.ABYSSAL_ORPHAN]: [],
    [EItem.UNSIRED]: [],
    [EItem.ABYSSAL_HEAD]: [],

    // Alchemical Hydra
    [EItem.HYDRAS_CLAW]: [],
    [EItem.HYDRA_TAIL]: [],
    [EItem.HYDRA_LEATHER]: [],
    [EItem.JAR_OF_CHEMICALS]: [],
    [EItem.IKKLE_HYDRA]: [],
    [EItem.HYDRAS_FANG]: [],
    [EItem.HYDRAS_EYE]: [],
    [EItem.HYDRAS_HEART]: [],
    [EItem.ALCHEMICAL_HYDRA_HEADS]: [],

    // Amoxliatl
    [EItem.MOXI]: [],
    [EItem.GLACIAL_TEMOTLI]: [],
    [EItem.PENDANT_OF_ATES_INERT]: [],

    // Araxxor
    [EItem.NID]: [],
    [EItem.ARAXYTE_FANG]: [],
    [EItem.NOXIOUS_POINT]: [],
    [EItem.NOXIOUS_BLADE]: [],
    [EItem.NOXIOUS_POMMEL]: [],
    [EItem.ARAXYTE_HEAD]: [],
    [EItem.JAR_OF_VENOM]: [],

    // Barrows
    [EItem.KARILS_COIF]: [],
    [EItem.KARILS_LEATHERTOP]: [],
    [EItem.KARILS_LEATHERSKIRT]: [],
    [EItem.KARILS_CROSSBOW]: [],

    [EItem.AHRIMS_HOOD]: [],
    [EItem.AHRIMS_ROBETOP]: [],
    [EItem.AHRIMS_ROBESKIRT]: [],
    [EItem.AHRIMS_STAFF]: [],

    [EItem.DHAROKS_HELM]: [],
    [EItem.DHAROKS_PLATEBODY]: [],
    [EItem.DHAROKS_PLATELEGS]: [],
    [EItem.DHAROKS_GREATAXE]: [],

    [EItem.GUTHANS_HELM]: [],
    [EItem.GUTHANS_PLATEBODY]: [],
    [EItem.GUTHANS_CHAINSKIRT]: [],
    [EItem.GUTHANS_WARSPEAR]: [],

    [EItem.TORAGS_HELM]: [],
    [EItem.TORAGS_PLATEBODY]: [],
    [EItem.TORAGS_PLATELEGS]: [],
    [EItem.TORAGS_HAMMERS]: [],

    [EItem.VERACS_HELM]: [],
    [EItem.VERACS_BRASSARD]: [],
    [EItem.VERACS_PLATESKIRT]: [],
    [EItem.VERACS_FLAIL]: [],

    // Bryophyta
    [EItem.BRYOPHYTAS_ESSENCE]: [],

    // Wilderness bosses
    // Callisto and Artio
    [EItem.TYRANNICAL_RING]: [EMonster.CALLISTO, EMonster.ARTIO],
    [EItem.CLAWS_OF_CALLISTO]: [EMonster.CALLISTO, EMonster.ARTIO],
    [EItem.VOIDWAKER_HILT]: [EMonster.CALLISTO, EMonster.ARTIO],
    [EItem.CALLISTO_CUB]: [],

    // Venenatis and Spindel
    [EItem.TREASONOUS_RING]: [EMonster.VENENATIS, EMonster.SPINDEL],
    [EItem.FANGS_OF_VENENATIS]: [EMonster.VENENATIS, EMonster.SPINDEL],
    [EItem.VOIDWAKER_GEM]: [EMonster.VENENATIS, EMonster.SPINDEL],
    [EItem.VENENATIS_SPIDERLING]: [],

    // Vet'ion and Calvar'ion
    [EItem.RING_OF_THE_GODS]: [EMonster.VETION, EMonster.CALVARION],
    [EItem.SKULL_OF_VETION]: [EMonster.VETION, EMonster.CALVARION],
    [EItem.VOIDWAKER_BLADE]: [EMonster.VETION, EMonster.CALVARION],
    [EItem.VETION_JR]: [],

    // Cerberus
    [EItem.ETERNAL_CRYSTAL]: [],
    [EItem.PEGASIAN_CRYSTAL]: [],
    [EItem.PRIMORDIAL_CRYSTAL]: [],
    [EItem.SMOULDERING_STONE]: [EMonster.CERBERUS, EMonster.HELLHOUND],
    [EItem.JAR_OF_SOULS]: [],
    [EItem.HELLPUPPY]: [],

    // Chaos Fanatic
    [EItem.ODIUM_SHARD_1]: [],
    [EItem.MALEDICTION_SHARD_1]: [],
    [EItem.PET_CHAOS_ELEMENTAL]: [
        EMonster.CHAOS_ELEMENTAL,
        EMonster.CHAOS_FANATIC,
    ],

    // Crazy Archaeologist
    [EItem.ODIUM_SHARD_2]: [],
    [EItem.MALEDICTION_SHARD_2]: [],

    // Scorpia
    [EItem.ODIUM_SHARD_3]: [],
    [EItem.MALEDICTION_SHARD_3]: [],
    [EItem.SCORPIAS_OFFSPRING]: [],

    // Corporeal Beast
    [EItem.ELYSIAN_SIGIL]: [],
    [EItem.SPECTRAL_SIGIL]: [],
    [EItem.ARCANE_SIGIL]: [],
    [EItem.HOLY_ELIXIR]: [],
    [EItem.SPIRIT_SHIELD]: [],
    [EItem.PET_DARK_CORE]: [],

    // Dagannoth Kings
    [EItem.BERSERKER_RING]: [],
    [EItem.ARCHERS_RING]: [],
    [EItem.SEERS_RING]: [],
    [EItem.WARRIOR_RING]: [],
    [EItem.SEERCULL]: [],
    [EItem.MUD_BATTLESTAFF]: [],
    [EItem.PET_DAGANNOTH_PRIME]: [],
    [EItem.PET_DAGANNOTH_SUPREME]: [],
    [EItem.PET_DAGANNOTH_REX]: [],

    // Doom of Mokhaiotl
    [EItem.MOKHAIOTL_WAYSTONE]: [],
    [EItem.AVERNIC_TREADS]: [],
    [EItem.EYE_OF_AYAK_UNCHARGED]: [],
    [EItem.MOKHAIOTL_CLOTH]: [],
    [EItem.DOM]: [],

    // Fortis Colosseum
    [EItem.SUNFIRE_FANATIC_CUIRASS]: [],
    [EItem.SUNFIRE_FANATIC_CHAUSSES]: [],
    [EItem.SUNFIRE_FANATIC_HELM]: [],
    [EItem.ECHO_CRYSTAL]: [],
    [EItem.TONALZTICS_OF_RALOS_UNCHARGED]: [],
    [EItem.SMOL_HEREDIT]: [],

    // The Gauntlet
    [EItem.CRYSTAL_ARMOUR_SEED]: [],
    [EItem.CRYSTAL_WEAPON_SEED]: [],
    [EItem.ENHANCED_CRYSTAL_WEAPON_SEED]: [],
    [EItem.YOUNGLLEF]: [],

    // Grotesque Guardians
    [EItem.BLACK_TOURMALINE_CORE]: [],
    [EItem.GRANITE_GLOVES]: [],
    [EItem.GRANITE_RING]: [],
    [EItem.GRANITE_HAMMER]: [],
    [EItem.NOON]: [],

    // Hespori
    [EItem.BOTTOMLESS_COMPOST_BUCKET]: [],

    // The Hueycoatl
    [EItem.HUBERTE]: [],
    [EItem.DRAGON_HUNTER_WAND]: [],
    [EItem.TOME_OF_EARTH]: [],
    [EItem.HUEYCOATL_HIDE]: [],

    // Kalphite Queen
    [EItem.JAR_OF_SAND]: [],
    [EItem.KALPHITE_PRINCESS]: [],

    // King Black Dragon
    [EItem.DRACONIC_VISAGE]: [EMonster.KING_BLACK_DRAGON, EMonster.VORKATH__2],
    [EItem.PRINCE_BLACK_DRAGON]: [],

    // Kraken
    [EItem.KRAKEN_TENTACLE]: [EMonster.KRAKEN, EMonster.CAVE_KRAKEN],
    [EItem.TRIDENT_OF_THE_SEAS_FULL]: [],
    [EItem.JAR_OF_DIRT]: [],
    [EItem.PET_KRAKEN]: [],

    // Moons of Peril
    [EItem.ECLIPSE_MOON_CHESTPLATE]: [],
    [EItem.ECLIPSE_MOON_TASSETS]: [],
    [EItem.ECLIPSE_MOON_HELM]: [],
    [EItem.ECLIPSE_ATLATL]: [],

    [EItem.BLUE_MOON_CHESTPLATE]: [],
    [EItem.BLUE_MOON_TASSETS]: [],
    [EItem.BLUE_MOON_HELM]: [],
    [EItem.BLUE_MOON_SPEAR]: [],

    [EItem.BLOOD_MOON_CHESTPLATE]: [],
    [EItem.BLOOD_MOON_TASSETS]: [],
    [EItem.BLOOD_MOON_HELM]: [],
    [EItem.DUAL_MACUAHUITL]: [],

    // The Nightmare
    [EItem.INQUISITORS_MACE]: [],
    [EItem.INQUISITORS_GREAT_HELM]: [],
    [EItem.INQUISITORS_HAUBERK]: [],
    [EItem.INQUISITORS_PLATESKIRT]: [],
    [EItem.NIGHTMARE_STAFF]: [],
    [EItem.VOLATILE_ORB]: [],
    [EItem.HARMONISED_ORB]: [],
    [EItem.ELDRITCH_ORB]: [],
    [EItem.JAR_OF_DREAMS]: [],
    [EItem.LITTLE_NIGHTMARE]: [],

    // Obor
    [EItem.HILL_GIANT_CLUB]: [],

    // Phantom Muspah
    [EItem.MUPHIN]: [],
    [EItem.VENATOR_SHARD]: [],
    [EItem.ANCIENT_ICON]: [],

    // Royal Titans
    [EItem.BRAN]: [],
    [EItem.DEADEYE_PRAYER_SCROLL]: [],
    [EItem.MYSTIC_VIGOUR_PRAYER_SCROLL]: [],
    [EItem.GIANTSOUL_AMULET]: [],
    [EItem.ICE_ELEMENT_STAFF_CROWN]: [],
    [EItem.FIRE_ELEMENT_STAFF_CROWN]: [],

    // Sarachnis
    [EItem.JAR_OF_EYES]: [],
    [EItem.SARACHNIS_CUDGEL]: [],
    [EItem.SRARACHA]: [],

    // Scurrius
    [EItem.SCURRIUS_SPINE]: [],
    [EItem.SCURRY]: [],

    // Skotizo
    [EItem.JAR_OF_DARKNESS]: [],
    [EItem.DARK_CLAW]: [],
    [EItem.SKOTOS]: [],

    // Thermonuclear Smoke Devil
    [EItem.PET_SMOKE_DEVIL]: [],
    [EItem.OCCULT_NECKLACE]: [
        EMonster.THERMONUCLEAR_SMOKE_DEVIL,
        EMonster.SMOKE_DEVIL,
    ],
    [EItem.SMOKE_BATTLESTAFF]: [],
    [EItem.JAR_OF_SMOKE]: [],

    // Vorkath
    [EItem.VORKI]: [],
    [EItem.SKELETAL_VISAGE]: [EMonster.VORKATH__2],
    [EItem.JAR_OF_DECAY]: [],
    [EItem.DRAGONBONE_NECKLACE]: [],

    // Yama
    [EItem.YAMI]: [],
    [EItem.OATHPLATE_HELM]: [],
    [EItem.OATHPLATE_CHEST]: [],
    [EItem.OATHPLATE_LEGS]: [],
    [EItem.SOULFLAME_HORN]: [],

    // Zulrah
    [EItem.PET_SNAKELING]: [],
    [EItem.TANZANITE_MUTAGEN]: [],
    [EItem.MAGMA_MUTAGEN]: [],
    [EItem.JAR_OF_SWAMP]: [],
    [EItem.MAGIC_FANG]: [],
    [EItem.SERPENTINE_VISAGE]: [],
    [EItem.TANZANITE_FANG]: [],

    // Bosses shared
    [EItem.DRAGON_CHAINBODY__2]: [
        EMonster.KALPHITE_QUEEN,
        EMonster.THERMONUCLEAR_SMOKE_DEVIL,
        EMonster.CHOKE_DEVIL,
        EMonster.NUCLEAR_SMOKE_DEVIL,
        EMonster.DUST_DEVIL,
        EMonster.SMOKE_DEVIL,
    ],
    [EItem.DRAGON_2H_SWORD]: [
        EMonster.CHAOS_ELEMENTAL,
        EMonster.SCORPIA,
        EMonster.CALLISTO,
        EMonster.KALPHITE_QUEEN,
        EMonster.VENENATIS__2,
        EMonster.VETION,
        EMonster.ARTIO,
        EMonster.CALVARION,
        EMonster.SPINDEL,
    ],
    [EItem.DRAGON_PICKAXE]: [
        EMonster.CHAOS_ELEMENTAL,
        EMonster.CALLISTO__2,
        EMonster.KALPHITE_QUEEN,
        EMonster.VENENATIS__2,
        EMonster.VETION__2,
        EMonster.ARTIO,
        EMonster.CALVARION,
        EMonster.SPINDEL,
        EMonster.KING_BLACK_DRAGON,
    ],

    // Slayer
    [EItem.CRAWLING_HAND__2]: [],
    [EItem.COCKATRICE_HEAD]: [],
    [EItem.BASILISK_HEAD]: [],
    [EItem.KURASK_HEAD]: [],
    [EItem.ETERNAL_GEM]: [],
    [EItem.IMBUED_HEART]: [],
    [EItem.DUST_BATTLESTAFF]: [],
    [EItem.MIST_BATTLESTAFF]: [],
    [EItem.DARK_BOW]: [],
    [EItem.BASILISK_JAW]: [],
    [EItem.WARPED_SCEPTRE_UNCHARGED]: [],
    [EItem.DAGONHAI_HAT]: [],
    [EItem.DAGONHAI_ROBE_TOP]: [],
    [EItem.DAGONHAI_ROBE_BOTTOM]: [],
    [EItem.BELLES_FOLLY_TARNISHED]: [],
    [EItem.HORN_OF_PLENTY_EMPTY]: [],
    [EItem.GULL]: [],
    [EItem.JAR_OF_FEATHERS]: [],
    [EItem.AQUANITE_TENDON]: [],

    // Elder Chaos Druids
    [EItem.ELDER_CHAOS_TOP]: [],
    [EItem.ELDER_CHAOS_ROBE]: [],
    [EItem.ELDER_CHAOS_HOOD]: [],

    // Revenants
    [EItem.VIGGORAS_CHAINMACE_U]: [],
    [EItem.CRAWS_BOW_U]: [],
    [EItem.THAMMARONS_SCEPTRE_U]: [],
    [EItem.AMULET_OF_AVARICE]: [],
    [EItem.ANCIENT_RELIC]: [],
    [EItem.ANCIENT_EFFIGY]: [],
    [EItem.ANCIENT_MEDALLION]: [],
    [EItem.ANCIENT_STATUETTE]: [],
    [EItem.ANCIENT_TOTEM]: [],
    [EItem.ANCIENT_EMBLEM]: [],

    // Tormented Demons
    [EItem.TORMENTED_SYNAPSE]: [],
    [EItem.BURNING_CLAW]: [],

    // Tzhaar
    [EItem.OBSIDIAN_CAPE]: [],
    [EItem.TOKTZKETXIL]: [],
    [EItem.TZHAARKETOM]: [],
    [EItem.TOKTZXILAK]: [],
    [EItem.TOKTZXILEK]: [],
    [EItem.TOKTZMEJTAL]: [],
    [EItem.TOKTZXILUL]: [],
    [EItem.OBSIDIAN_HELMET]: [],
    [EItem.OBSIDIAN_PLATEBODY]: [],
    [EItem.OBSIDIAN_PLATELEGS]: [],

    // Misc
    [EItem.DRAGON_WARHAMMER]: [],

    [EItem.FISH_BARREL]: [],
    [EItem.DRAGON_AXE]: [],
    [EItem.ZENYTE_SHARD]: [],

    // Clue Scrolls
    // Easy
    [EItem.A_POWDERED_WIG]: [],
    [EItem.ANCIENT_ROBE_LEGS]: [],
    [EItem.ANCIENT_ROBE_TOP]: [],
    [EItem.ARMADYL_ROBE_LEGS]: [],
    [EItem.ARMADYL_ROBE_TOP]: [],
    [EItem.BANDOS_ROBE_LEGS]: [],
    [EItem.BANDOS_ROBE_TOP]: [],
    [EItem.BEANIE]: [],
    [EItem.BLACK_BERET]: [],
    [EItem.BLACK_CANE]: [],
    [EItem.BLACK_FULL_HELM_G]: [],
    [EItem.BLACK_FULL_HELM_T]: [],
    [EItem.BLACK_HELM_H1]: [],
    [EItem.BLACK_HELM_H2]: [],
    [EItem.BLACK_HELM_H3]: [],
    [EItem.BLACK_HELM_H4]: [],
    [EItem.BLACK_HELM_H5]: [],
    [EItem.BLACK_KITESHIELD_G]: [],
    [EItem.BLACK_KITESHIELD_T]: [],
    [EItem.BLACK_PLATEBODY_G]: [],
    [EItem.BLACK_PLATELEGS_G]: [],
    [EItem.BLACK_PLATESKIRT_G]: [],
    [EItem.BLACK_PLATESKIRT_T]: [],
    [EItem.BLACK_SKIRT_G]: [],
    [EItem.BLACK_SKIRT_T]: [],
    [EItem.BLACK_WIZARD_HAT_G]: [],
    [EItem.BLACK_WIZARD_HAT_T]: [],
    [EItem.BLACK_WIZARD_ROBE_G]: [],
    [EItem.BLACK_WIZARD_ROBE_T]: [],
    [EItem.BLUE_BERET]: [],
    [EItem.BLUE_SKIRT_G]: [],
    [EItem.BLUE_SKIRT_T]: [],
    [EItem.BLUE_WIZARD_HAT_G]: [],
    [EItem.BLUE_WIZARD_HAT_T]: [],
    [EItem.BLUE_WIZARD_ROBE_G]: [],
    [EItem.BLUE_WIZARD_ROBE_T]: [],
    [EItem.BOBS_RED_SHIRT]: [],
    [EItem.BOBS_BLUE_SHIRT]: [],
    [EItem.BOBS_GREEN_SHIRT]: [],
    [EItem.BOBS_BLACK_SHIRT]: [],
    [EItem.BOBS_PURPLE_SHIRT]: [],
    [EItem.BRONZE_FULL_HELM_G]: [],
    [EItem.BRONZE_FULL_HELM_T]: [],
    [EItem.BRONZE_KITESHIELD_G]: [],
    [EItem.BRONZE_KITESHIELD_T]: [],
    [EItem.BRONZE_PLATEBODY_G]: [],
    [EItem.BRONZE_PLATEBODY_T]: [],
    [EItem.BRONZE_PLATELEGS_G]: [],
    [EItem.BRONZE_PLATELEGS_T]: [],
    [EItem.BRONZE_PLATESKIRT_G]: [],
    [EItem.BRONZE_PLATESKIRT_T]: [],
    [EItem.FLARED_TROUSERS]: [],
    [EItem.GOBLIN_MASK]: [],
    [EItem.GUTHIX_ROBE_LEGS]: [],
    [EItem.GUTHIX_ROBE_TOP]: [],
    [EItem.HIGHWAYMAN_MASK]: [],
    [EItem.IMP_MASK]: [],
    [EItem.IRON_FULL_HELM_G]: [],
    [EItem.IRON_FULL_HELM_T]: [],
    [EItem.IRON_KITESHIELD_G]: [],
    [EItem.IRON_KITESHIELD_T]: [],
    [EItem.IRON_PLATEBODY_G]: [],
    [EItem.IRON_PLATEBODY_T]: [],
    [EItem.IRON_PLATELEGS_G]: [],
    [EItem.IRON_PLATELEGS_T]: [],
    [EItem.IRON_PLATESKIRT_G]: [],
    [EItem.IRON_PLATESKIRT_T]: [],
    [EItem.LEATHER_BODY_G]: [],
    [EItem.LEATHER_CHAPS_G]: [],
    [EItem.PANTALOONS]: [],
    [EItem.RAIN_BOW]: [],
    [EItem.RED_BERET]: [],
    [EItem.SARADOMIN_ROBE_LEGS]: [],
    [EItem.SARADOMIN_ROBE_TOP]: [],
    [EItem.SLEEPING_CAP]: [],
    [EItem.STAFF_OF_BOB_THE_CAT]: [],
    [EItem.STEEL_PLATEBODY_G]: [],
    [EItem.STEEL_PLATEBODY_T]: [],
    [EItem.STEEL_FULL_HELM_G]: [],
    [EItem.STEEL_FULL_HELM_T]: [],
    [EItem.STEEL_KITESHIELD_G]: [],
    [EItem.STEEL_KITESHIELD_T]: [],
    [EItem.STEEL_PLATELEGS_G]: [],
    [EItem.STEEL_PLATELEGS_T]: [],
    [EItem.STEEL_PLATESKIRT_G]: [],
    [EItem.STEEL_PLATESKIRT_T]: [],
    [EItem.STUDDED_BODY_G]: [],
    [EItem.STUDDED_BODY_T]: [],
    [EItem.STUDDED_CHAPS_G]: [],
    [EItem.STUDDED_CHAPS_T]: [],
    [EItem.WHITE_BERET]: [],
    [EItem.WILLOW_LONGBOW]: [],
    [EItem.WILLOW_COMP_BOW]: [],
    [EItem.WOODEN_SHIELD_G]: [],
    [EItem.ZAMORAK_ROBE_LEGS]: [],
    [EItem.ZAMORAK_ROBE_TOP]: [],

    // Medium
    [EItem.ADAMANT_CANE]: [],
    [EItem.ADAMANT_FULL_HELM_G]: [],
    [EItem.ADAMANT_FULL_HELM_T]: [],
    [EItem.ADAMANT_HELM_H1]: [],
    [EItem.ADAMANT_HELM_H2]: [],
    [EItem.ADAMANT_HELM_H3]: [],
    [EItem.ADAMANT_HELM_H4]: [],
    [EItem.ADAMANT_HELM_H5]: [],
    [EItem.ADAMANT_KITESHIELD_G]: [],
    [EItem.ADAMANT_KITESHIELD_T]: [],
    [EItem.ADAMANT_PLATEBODY_G]: [],
    [EItem.ADAMANT_PLATEBODY_T]: [],
    [EItem.ADAMANT_PLATEBODY_H1]: [],
    [EItem.ADAMANT_PLATEBODY_H2]: [],
    [EItem.ADAMANT_PLATEBODY_H3]: [],
    [EItem.ADAMANT_PLATEBODY_H4]: [],
    [EItem.ADAMANT_PLATEBODY_H5]: [],
    [EItem.ADAMANT_PLATELEGS_G]: [],
    [EItem.ADAMANT_PLATELEGS_T]: [],
    [EItem.ADAMANT_PLATESKIRT_G]: [],
    [EItem.ADAMANT_PLATESKIRT_T]: [],
    [EItem.ADAMANT_SHIELD_H1]: [],
    [EItem.ADAMANT_SHIELD_H2]: [],
    [EItem.ADAMANT_SHIELD_H3]: [],
    [EItem.ADAMANT_SHIELD_H4]: [],
    [EItem.ADAMANT_SHIELD_H5]: [],
    [EItem.ANCIENT_CLOAK]: [],
    [EItem.ANCIENT_MITRE]: [],
    [EItem.ANCIENT_STAFF]: [],
    [EItem.ANCIENT_STOLE]: [],
    [EItem.ARCEUUS_BANNER]: [],
    [EItem.ARMADYL_CLOAK]: [],
    [EItem.ARMADYL_MITRE]: [],
    [EItem.ARMADYL_STOLE]: [],
    [EItem.BANDOS_CLOAK]: [],
    [EItem.BANDOS_MITRE]: [],
    [EItem.BANDOS_STOLE]: [],
    [EItem.BLACK_BOATER]: [],
    [EItem.BLACK_ELEGANT_LEGS]: [],
    [EItem.BLACK_ELEGANT_SHIRT]: [],
    [EItem.BLACK_HEADBAND]: [],
    [EItem.BLACK_LEPRECHAUN_HAT]: [],
    [EItem.BLUE_BOATER]: [],
    [EItem.BLUE_HEADBAND]: [],
    [EItem.BROWN_HEADBAND]: [],
    [EItem.CAT_MASK]: [],
    [EItem.CLIMBING_BOOTS_G]: [],
    [EItem.CRIER_BELL]: [],
    [EItem.CRIER_COAT]: [],
    [EItem.CRIER_HAT]: [],
    [EItem.GOLD_ELEGANT_BLOUSE]: [],
    [EItem.GOLD_ELEGANT_LEGS]: [],
    [EItem.GOLD_ELEGANT_SHIRT]: [],
    [EItem.GOLD_ELEGANT_SKIRT]: [],
    [EItem.GOLD_HEADBAND]: [],
    [EItem.GREEN_BOATER]: [],
    [EItem.GREEN_DHIDE_BODY_G]: [],
    [EItem.GREEN_DHIDE_BODY_T]: [],
    [EItem.GREEN_DHIDE_CHAPS_G]: [],
    [EItem.GREEN_DHIDE_CHAPS_T]: [],
    [EItem.GREEN_HEADBAND]: [],
    [EItem.GUTHIX_CLOAK]: [],
    [EItem.GUTHIX_MITRE]: [],
    [EItem.HOLY_SANDALS]: [],
    [EItem.HOSIDIUS_BANNER]: [],
    [EItem.LEPRECHAUN_HAT]: [],
    [EItem.LOVAKENGJ_BANNER]: [],
    [EItem.MITHRIL_FULL_HELM_G]: [],
    [EItem.MITHRIL_FULL_HELM_T]: [],
    [EItem.MITHRIL_KITESHIELD_G]: [],
    [EItem.MITHRIL_KITESHIELD_T]: [],
    [EItem.MITHRIL_PLATEBODY_G]: [],
    [EItem.MITHRIL_PLATEBODY_T]: [],
    [EItem.MITHRIL_PLATELEGS_G]: [],
    [EItem.MITHRIL_PLATELEGS_T]: [],
    [EItem.MITHRIL_PLATESKIRT_G]: [],
    [EItem.MITHRIL_PLATESKIRT_T]: [],
    [EItem.ORANGE_BOATER]: [],
    [EItem.PENGUIN_MASK]: [],
    [EItem.PINK_BOATER]: [],
    [EItem.PINK_ELEGANT_BLOUSE]: [],
    [EItem.PINK_ELEGANT_LEGS]: [],
    [EItem.PINK_ELEGANT_SHIRT]: [],
    [EItem.PINK_ELEGANT_SKIRT]: [],
    [EItem.PINK_HEADBAND]: [],
    [EItem.PISCARILIUS_BANNER]: [],
    [EItem.PURPLE_BOATER]: [],
    [EItem.PURPLE_ELEGANT_BLOUSE]: [],
    [EItem.PURPLE_ELEGANT_LEGS]: [],
    [EItem.PURPLE_ELEGANT_SHIRT]: [],
    [EItem.PURPLE_ELEGANT_SKIRT]: [],
    [EItem.RANGER_BOOTS]: [],
    [EItem.RED_BOATER]: [],
    [EItem.RED_HEADBAND]: [],
    [EItem.SARADOMIN_CLOAK]: [],
    [EItem.SARADOMIN_MITRE]: [],
    [EItem.SHAYZIEN_BANNER]: [],
    [EItem.SPIKED_MANACLES]: [],
    [EItem.WHITE_BOATER]: [],
    [EItem.WHITE_HEADBAND]: [],
    [EItem.WOLF_CLOAK]: [],
    [EItem.WOLF_MASK]: [],
    [EItem.ZAMORAK_CLOAK]: [],
    [EItem.ZAMORAK_MITRE]: [],

    // Hard
    [EItem._3RD_AGE_RANGE_COIF]: [],
    [EItem._3RD_AGE_RANGE_TOP]: [],
    [EItem._3RD_AGE_RANGE_LEGS]: [],
    [EItem._3RD_AGE_VAMBRACES]: [],
    [EItem._3RD_AGE_ROBE_TOP]: [],
    [EItem._3RD_AGE_ROBE]: [],
    [EItem._3RD_AGE_MAGE_HAT]: [],
    [EItem._3RD_AGE_AMULET]: [],
    [EItem._3RD_AGE_PLATELEGS]: [],
    [EItem._3RD_AGE_PLATEBODY]: [],
    [EItem._3RD_AGE_FULL_HELMET]: [],
    [EItem._3RD_AGE_PLATESKIRT]: [],
    [EItem._3RD_AGE_KITESHIELD]: [],
    [EItem.AMULET_OF_GLORY_T]: [],
    [EItem.ANCIENT_BRACERS]: [],
    [EItem.ANCIENT_CHAPS]: [],
    [EItem.ANCIENT_COIF]: [],
    [EItem.ANCIENT_DHIDE_BOOTS]: [],
    [EItem.ANCIENT_FULL_HELM]: [],
    [EItem.ANCIENT_KITESHIELD]: [],
    [EItem.ANCIENT_PLATEBODY]: [],
    [EItem.ANCIENT_PLATELEGS]: [],
    [EItem.ANCIENT_PLATESKIRT]: [],
    [EItem.ARMADYL_BRACERS]: [],
    [EItem.ARMADYL_CHAPS]: [],
    [EItem.ARMADYL_COIF]: [],
    [EItem.ARMADYL_DHIDE_BOOTS]: [],
    [EItem.ARMADYL_FULL_HELM]: [],
    [EItem.ARMADYL_KITESHIELD]: [],
    [EItem.ARMADYL_PLATEBODY]: [],
    [EItem.ARMADYL_PLATELEGS]: [],
    [EItem.ARMADYL_PLATESKIRT]: [],
    [EItem.BANDOS_BRACERS]: [],
    [EItem.BANDOS_CHAPS]: [],
    [EItem.BANDOS_COIF]: [],
    [EItem.BANDOS_DHIDE_BOOTS]: [],
    [EItem.BANDOS_FULL_HELM]: [],
    [EItem.BANDOS_KITESHIELD]: [],
    [EItem.BANDOS_PLATEBODY]: [],
    [EItem.BANDOS_PLATELEGS]: [],
    [EItem.BANDOS_PLATESKIRT]: [],
    [EItem.BERSERKER_NECKLACE_ORNAMENT_KIT]: [],
    [EItem.BLACK_CAVALIER]: [],
    [EItem.BLACK_DHIDE_BODY_G]: [],
    [EItem.BLACK_DHIDE_BODY_T]: [],
    [EItem.BLACK_DHIDE_CHAPS_G]: [],
    [EItem.BLACK_DHIDE_CHAPS_T]: [],
    [EItem.BLACK_DRAGON_MASK]: [],
    [EItem.BLUE_DHIDE_BODY_G]: [],
    [EItem.BLUE_DHIDE_BODY_T]: [],
    [EItem.BLUE_DHIDE_CHAPS_G]: [],
    [EItem.BLUE_DHIDE_CHAPS_T]: [],
    [EItem.BLUE_DRAGON_MASK]: [],
    [EItem.CYCLOPS_HEAD]: [],
    [EItem.DARK_CAVALIER]: [],
    [EItem.DRAGON_BOOTS_ORNAMENT_KIT]: [],
    [EItem.DUAL_SAI]: [],
    [EItem.ENCHANTED_HAT]: [],
    [EItem.ENCHANTED_TOP]: [],
    [EItem.ENCHANTED_ROBE]: [],
    [EItem.EXPLORER_BACKPACK]: [],
    [EItem.GREEN_DRAGON_MASK]: [],
    [EItem.GUTHIX_BRACERS]: [],
    [EItem.GUTHIX_CHAPS]: [],
    [EItem.GUTHIX_COIF]: [],
    [EItem.GUTHIX_CROZIER]: [],
    [EItem.GUTHIX_DHIDE_BOOTS]: [],
    [EItem.GUTHIX_STOLE]: [],
    [EItem.NAVY_CAVALIER]: [],
    [EItem.NUNCHAKU]: [],
    [EItem.PIRATE_HAT]: [],
    [EItem.PITH_HELMET]: [],
    [EItem.RED_CAVALIER]: [],
    [EItem.RED_DHIDE_BODY_G]: [],
    [EItem.RED_DHIDE_BODY_T]: [],
    [EItem.RED_DHIDE_CHAPS_G]: [],
    [EItem.RED_DHIDE_CHAPS_T]: [],
    [EItem.RED_DRAGON_MASK]: [],
    [EItem.ROBIN_HOOD_HAT]: [],
    [EItem.RUNE_CANE]: [],
    [EItem.RUNE_DEFENDER_ORNAMENT_KIT]: [],
    [EItem.RUNE_FULL_HELM_G]: [],
    [EItem.RUNE_FULL_HELM_T]: [],
    [EItem.RUNE_HELM_H1]: [],
    [EItem.RUNE_HELM_H2]: [],
    [EItem.RUNE_HELM_H3]: [],
    [EItem.RUNE_HELM_H4]: [],
    [EItem.RUNE_HELM_H5]: [],
    [EItem.RUNE_KITESHIELD_G]: [],
    [EItem.RUNE_KITESHIELD_T]: [],
    [EItem.RUNE_PLATEBODY_G]: [],
    [EItem.RUNE_PLATEBODY_T]: [],
    [EItem.RUNE_PLATELEGS_G]: [],
    [EItem.RUNE_PLATELEGS_T]: [],
    [EItem.RUNE_PLATESKIRT_G]: [],
    [EItem.RUNE_PLATESKIRT_T]: [],
    [EItem.RUNE_SHIELD_H1]: [],
    [EItem.RUNE_SHIELD_H2]: [],
    [EItem.RUNE_SHIELD_H3]: [],
    [EItem.RUNE_SHIELD_H4]: [],
    [EItem.RUNE_SHIELD_H5]: [],
    [EItem.SARADOMIN_BRACERS]: [],
    [EItem.SARADOMIN_CHAPS]: [],
    [EItem.SARADOMIN_COIF]: [],
    [EItem.SARADOMIN_CROZIER]: [],
    [EItem.SARADOMIN_DHIDE_BOOTS]: [],
    [EItem.SARADOMIN_STOLE]: [],
    [EItem.TAN_CAVALIER]: [],
    [EItem.THIEVING_BAG]: [],
    [EItem.TZHAARKETOM_ORNAMENT_KIT]: [],
    [EItem.WHITE_CAVALIER]: [],
    [EItem.ZAMORAK_BRACERS]: [],
    [EItem.ZAMORAK_CHAPS]: [],
    [EItem.ZAMORAK_COIF]: [],
    [EItem.ZAMORAK_CROZIER]: [],
    [EItem.ZAMORAK_DHIDE_BOOTS]: [],
    [EItem.ZAMORAK_STOLE]: [],
    [EItem.ZOMBIE_HEAD]: [],

    // Elite
    [EItem._3RD_AGE_BOW]: [],
    [EItem._3RD_AGE_CLOAK]: [],
    [EItem._3RD_AGE_LONGSWORD]: [],
    [EItem._3RD_AGE_WAND]: [],
    [EItem.ADAMANT_DRAGON_MASK]: [],
    [EItem.AFRO]: [],
    [EItem.ARCEUUS_SCARF]: [],
    [EItem.BATTLESTAFF]: [],
    [EItem.BLACKSMITHS_HELM]: [],
    [EItem.BRIEFCASE]: [],
    [EItem.BRONZE_DRAGON_MASK]: [],
    [EItem.BUCKET_HELM]: [],
    [EItem.CRYSTAL_KEY]: [],
    [EItem.DARK_INFINITY_COLOUR_KIT]: [],
    [EItem.DEERSTALKER]: [],
    [EItem.DRAGON_CANE]: [],
    [EItem.DRAGON_CHAINBODY_ORNAMENT_KIT]: [],
    [EItem.DRAGON_FULL_HELM_ORNAMENT_KIT]: [],
    [EItem.DRAGON_SCIMITAR_ORNAMENT_KIT]: [],
    [EItem.DRAGON_SQ_SHIELD_ORNAMENT_KIT]: [],
    [EItem.EXTENDED_ANTIFIRE4]: [],
    [EItem.FREMENNIK_KILT]: [],
    [EItem.FURY_ORNAMENT_KIT]: [],
    [EItem.GIANT_BOOT]: [],
    [EItem.GILDED_AXE]: [],
    [EItem.GILDED_BOOTS]: [],
    [EItem.GILDED_DHIDE_CHAPS]: [],
    [EItem.GILDED_DHIDE_BODY]: [],
    [EItem.GILDED_DHIDE_VAMBRACES]: [],
    [EItem.GILDED_PICKAXE]: [],
    [EItem.GILDED_SCIMITAR]: [],
    [EItem.GILDED_SPADE]: [],
    [EItem.HOLY_WRAPS]: [],
    [EItem.HOSIDIUS_SCARF]: [],
    [EItem.IRON_DRAGON_MASK]: [],
    [EItem.KATANA]: [],
    [EItem.LAVA_DRAGON_MASK]: [],
    [EItem.LIGHT_INFINITY_COLOUR_KIT]: [],
    [EItem.LOVAKENGJ_SCARF]: [],
    [EItem.MITHRIL_DRAGON_MASK]: [],
    [EItem.MONOCLE]: [],
    [EItem.MUSKETEER_HAT]: [],
    [EItem.MUSKETEER_TABARD]: [],
    [EItem.MUSKETEER_PANTS]: [],
    [EItem.PISCARILIUS_SCARF]: [],
    [EItem.RANGER_GLOVES]: [],
    [EItem.RANGERS_TIGHTS]: [],
    [EItem.RING_OF_NATURE]: [],
    [EItem.ROYAL_CROWN]: [],
    [EItem.ROYAL_SCEPTRE]: [],
    [EItem.RUNE_DRAGON_MASK]: [],
    [EItem.SARADOMIN_BREW4]: [],
    [EItem.SHAYZIEN_SCARF]: [],
    [EItem.STEEL_DRAGON_MASK]: [],
    [EItem.SUPER_RESTORE4]: [],
    [EItem.TOP_HAT]: [],
    [EItem.URIS_HAT]: [],

    // Master
    [EItem._3RD_AGE_AXE]: [],
    [EItem._3RD_AGE_DRUIDIC_CLOAK]: [],
    [EItem._3RD_AGE_DRUIDIC_ROBE_TOP]: [],
    [EItem._3RD_AGE_DRUIDIC_ROBE_BOTTOMS]: [],
    [EItem._3RD_AGE_DRUIDIC_STAFF]: [],
    [EItem._3RD_AGE_PICKAXE]: [],
    [EItem.ALE_OF_THE_GODS]: [],
    [EItem.ARCEUUS_HOOD]: [],
    [EItem.BLACK_DEMON_MASK]: [],
    [EItem.BLACK_DRAGONHIDE]: [],
    [EItem.BOOTS_OF_DARKNESS]: [],
    [EItem.BOWL_WIG]: [],
    [EItem.BUCKET_HELM_G]: [],
    [EItem.CABBAGE]: [],
    [EItem.DRAGON_BATTLEAXE]: [],
    [EItem.DRAGON_DEFENDER_ORNAMENT_KIT]: [],
    [EItem.DRAGON_HALBERD]: [],
    [EItem.FANCY_TIARA]: [],
    [EItem.GILDED_CHAINBODY]: [],
    [EItem.GILDED_FULL_HELM]: [],
    [EItem.GILDED_HASTA]: [],
    [EItem.GILDED_KITESHIELD]: [],
    [EItem.GILDED_MED_HELM]: [],
    [EItem.GILDED_2H_SWORD]: [],
    [EItem.GILDED_SPEAR]: [],
    [EItem.GILDED_PLATEBODY]: [],
    [EItem.GILDED_PLATELEGS]: [],
    [EItem.GILDED_PLATESKIRT]: [],
    [EItem.GLOVES_OF_DARKNESS]: [],
    [EItem.GRIMY_RANARR_WEED]: [],
    [EItem.GRIMY_SNAPDRAGON]: [],
    [EItem.GRIMY_TOADFLAX]: [],
    [EItem.GREATER_DEMON_MASK]: [],
    [EItem.HALF_MOON_SPECTACLES]: [],
    [EItem.HOOD_OF_DARKNESS]: [],
    [EItem.HOSIDIUS_HOOD]: [],
    [EItem.JUNGLE_DEMON_MASK]: [],
    [EItem.LESSER_DEMON_MASK]: [],
    [EItem.LIMPWURT_ROOT]: [],
    [EItem.LOVAKENGJ_HOOD]: [],
    [EItem.OBSIDIAN_CAPE_R]: [],
    [EItem.OCCULT_ORNAMENT_KIT]: [],
    [EItem.OLD_DEMON_MASK]: [],
    [EItem.ONYX_BOLTS_E]: [],
    [EItem.PISCARILIUS_HOOD]: [],
    [EItem.RING_OF_COINS]: [],
    [EItem.ROBE_TOP_OF_DARKNESS]: [],
    [EItem.ROBE_BOTTOM_OF_DARKNESS]: [],
    [EItem.RUNITE_BAR]: [],
    [EItem.RUNITE_ORE]: [],
    [EItem.SAMURAI_BOOTS]: [],
    [EItem.SAMURAI_GLOVES]: [],
    [EItem.SAMURAI_KASA]: [],
    [EItem.SAMURAI_SHIRT]: [],
    [EItem.SAMURAI_GREAVES]: [],
    [EItem.SHAYZIEN_HOOD]: [],
    [EItem.TORMENTED_ORNAMENT_KIT]: [],
    [EItem.TORSTOL]: [],
    [EItem.TORTURE_ORNAMENT_KIT]: [],
    [EItem.WINE_OF_ZAMORAK]: [],

    // General (shared across all tiers)
    [EItem.ANCIENT_BLESSING]: [],
    [EItem.ANCIENT_PAGE_1]: [],
    [EItem.ANCIENT_PAGE_2]: [],
    [EItem.ANCIENT_PAGE_3]: [],
    [EItem.ANCIENT_PAGE_4]: [],
    [EItem.ARMADYL_PAGE_1]: [],
    [EItem.ARMADYL_PAGE_2]: [],
    [EItem.ARMADYL_PAGE_3]: [],
    [EItem.ARMADYL_PAGE_4]: [],
    [EItem.BANDOS_PAGE_1]: [],
    [EItem.BANDOS_PAGE_2]: [],
    [EItem.BANDOS_PAGE_3]: [],
    [EItem.BANDOS_PAGE_4]: [],
    [EItem.BLUE_FIRELIGHTER]: [],
    [EItem.GREEN_FIRELIGHTER]: [],
    [EItem.GUTHIX_PAGE_1]: [],
    [EItem.GUTHIX_PAGE_2]: [],
    [EItem.GUTHIX_PAGE_3]: [],
    [EItem.GUTHIX_PAGE_4]: [],
    [EItem.HOLY_BLESSING]: [],
    [EItem.HONOURABLE_BLESSING]: [],
    [EItem.LOOP_HALF_OF_KEY]: [],
    [EItem.NARDAH_TELEPORT]: [],
    [EItem.MORTTON_TELEPORT]: [],
    [EItem.FELDIP_HILLS_TELEPORT]: [],
    [EItem.LUNAR_ISLE_TELEPORT]: [],
    [EItem.DIGSITE_TELEPORT]: [],
    [EItem.PISCATORIS_TELEPORT]: [],
    [EItem.PEST_CONTROL_TELEPORT]: [],
    [EItem.TAI_BWO_WANNAI_TELEPORT]: [],
    [EItem.LUMBERYARD_TELEPORT]: [],
    [EItem.MOS_LEHARMLESS_TELEPORT]: [],
    [EItem.PEACEFUL_BLESSING]: [],
    [EItem.PURPLE_FIRELIGHTER]: [],
    [EItem.RED_FIRELIGHTER]: [],
    [EItem.SARADOMIN_PAGE_1]: [],
    [EItem.SARADOMIN_PAGE_2]: [],
    [EItem.SARADOMIN_PAGE_3]: [],
    [EItem.SARADOMIN_PAGE_4]: [],
    [EItem.UNHOLY_BLESSING]: [],
    [EItem.WAR_BLESSING]: [],
    [EItem.WHITE_FIRELIGHTER]: [],
    [EItem.ZAMORAK_PAGE_1]: [],
    [EItem.ZAMORAK_PAGE_2]: [],
    [EItem.ZAMORAK_PAGE_3]: [],
    [EItem.ZAMORAK_PAGE_4]: [],

};
